//! SeaORM entity models for the KabiPay database.
//!
//! - [`tenant`]: client-plane tables from Liquibase domains `0005`–`0030` (per-tenant schema).
//! - [`ops`]: selected `kabipay_ops` tables (e.g. global integration connector catalog).
//!
//! Tenant modules are generated by `scripts/generate_db_entities.py` from Liquibase XML.
//! Re-run the script after migration changes.

pub mod ops;
pub mod tenant;
